baseURL = 'https://d.oppara.tv/'
title = 'd.oppara.tv'
theme = "PaperMod"

timeZone = "Asia/Tokyo"
defaultContentLanguage = "ja"
languageCode = 'ja'
hasCJKLanguage = true
pluralizeListTitles = false

[security]
  [security.exec]
    allow = ['^vim$']

[permalinks]
    posts = "/:section/:year/:month/:filename"


[Params]
  author = "oppara"
  dateformat = "2006-01-02"
  hideSummary = true
  disableSpecial1stPost = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
