baseURL = 'http://example.org/'
title = 'My New Hugo Site'
theme = "PaperMod"

defaultContentLanguage = "ja"
languageCode = 'ja'
hasCJKLanguage = true
pluralizeListTitles = false


[permalinks]
    posts = "/:section/:year/:month/:filename"
