baseURL = 'http://example.org/'
title = 'd.oppara.tv'
theme = "PaperMod"

defaultContentLanguage = "ja"
languageCode = 'ja'
hasCJKLanguage = true
pluralizeListTitles = false

[security]
  [security.exec]
    allow = ['^vim$']

[permalinks]
    posts = "/:section/:year/:month/:filename"


[Params]
  dateformat = "2006-01-02"
